import pandas as pd
import os

def save_excel_report(df, results, status, deviations):
    os.makedirs("output", exist_ok=True)

    file_path = "output/report.xlsx"

    with pd.ExcelWriter(file_path, engine="openpyxl") as writer:

        # 🔹 Summary Sheet
        summary_data = {
            "Parameter": ["Temperature", "Temperature", "Temperature",
                          "Pressure", "Pressure", "Pressure"],
            "Metric": ["Min", "Max", "Average",
                       "Min", "Max", "Average"],
            "Value": [
                results["temp_min"],
                results["temp_max"],
                results["temp_avg"],
                results["press_min"],
                results["press_max"],
                results["press_avg"]
            ]
        }

        summary_df = pd.DataFrame(summary_data)
        summary_df.to_excel(writer, sheet_name="Summary", index=False)

        # 🔹 Status Sheet
        status_df = pd.DataFrame({
            "Status": [status],
            "Remarks": ["Auto generated by system"]
        })
        status_df.to_excel(writer, sheet_name="Status", index=False)

        # 🔹 Deviations Sheet
        if deviations:
            dev_df = pd.DataFrame({"Deviations": deviations})
        else:
            dev_df = pd.DataFrame({"Deviations": ["No deviations"]})

        dev_df.to_excel(writer, sheet_name="Deviations", index=False)

        # 🔹 Raw Data Sheet
        df.to_excel(writer, sheet_name="Raw Data", index=False)

    print(f"Report saved at {file_path}")